
name: Python UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest UI tests
      env:
        BASE_URL: https://www.saucedemo.com
        HEADLESS: "true"
      run: |
        pytest tests/ui --json-report --json-report-file=report-ui.json

    - name: Upload Pytest UI JSON Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-ui-json-report
        path: report-ui.json

    # Example of uploading an HTML report if pytest-html is used
    # - name: Generate HTML Report
    #   run: pytest --html=report.html --self-contained-html
    # - name: Upload Pytest HTML Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: pytest-html-report
    #     path: report.html
